"""zalupa 1

Revision ID: 5ca7f29bcf65
Revises: 
Create Date: 2023-05-21 01:22:15.293510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca7f29bcf65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('direction_1', sa.String(), nullable=False),
    sa.Column('direction_2', sa.String(), nullable=False),
    sa.Column('direction_3', sa.String(), nullable=False),
    sa.Column('event_address', sa.String(), nullable=False),
    sa.Column('big_district', sa.String(), nullable=False),
    sa.Column('small_district', sa.String(), nullable=False),
    sa.Column('open_schedule', sa.String(), nullable=True),
    sa.Column('close_schedule', sa.String(), nullable=False),
    sa.Column('plan_schedule', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('born_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('group')
    # ### end Alembic commands ###
